### ISSUE TITLE
Have a question on the DVS-Gait-Night dataset

### ISSUE THREAD

**Issue by MrFisher97** [zhangxiann/TPAMI_Gait_Identification#1]
From the link of the DVS-Gait-Night dataset you provided, I find the number of each object is under 200.  So I want to know If there exists any difference between the dataset you upload from your description of this dataset.

**Comment by zhangxiann** [comment]
Hello, I have pointed out the difference in the readme.
> For each lighting condition, we recruited 20 volunteers to contribute their data **in two experiment sessions spanning over a few days**. In each session, the participants were asked to repeat walking in front of the DVS128 sensor for 100 times.

**Comment by MrFisher97** [comment]
Thank you for your reply! But I still feel confused if the sample number of each participant in the DVS-Gait-Night dataset is 200, because, from the README, you say there exist two sessions and each participant was asked to repeat walking 100 times in each session.

**Comment by zhangxiann** [comment]
For each person, he/she repeat walking 100 times in first session; then after several days, he repeat walking 100 times in second session. So the total number is 100+100 =200. 

`indoor_night1` folder is the data collected in the first session. 
`indoor_night2` folder is the data collected in the second session.

**Comment by MrFisher97** [comment]
That means in the `indoor_night2` dataset, there exist 100 data recoding files in each person's folder, e.g. in the '0xh' folder, right? But I find there exist only 23 files in the '0xh' folder of the `indoor_night2` dataset, and this situation exists in other folders of the 'indoor_night2' dataset which I downloaded from the link https://pan.baidu.com/s/1txWR75DaAOyva6oUOJ4Kbg. That link is what you put on the README.

**Comment by zhangxiann** [comment]
I'm sorry there's something wrong with the DVS-Gait-Night dataset we shared. I will reupload the data and let you know soon .

**Comment by zhangxiann** [comment]
I update the link of DVS-Gait-Night, you can now download the complete DVS-Gait-Night dataset.

**Comment by MrFisher97** [comment]
Thank you for your response and the dataset you provided is complete now.
