### ISSUE TITLE
How to control the num of the events after downsample

### ISSUE THREAD

**Issue by Hanwey2333** [zhangxiann/TPAMI_Gait_Identification#4]
下采样后的单个数据文件的事件信息数据量都为2048，但是matlab和python代码看起来无法控制事件信息数量为2048，想问一下如何控制事件信息数量

**Comment by zhangxiann** [comment]
降采样后每个文件的 event 数量不是固定 2048，只是平均 2048。

**Comment by zhangxiann** [comment]
如果你想控制降采样后的事件数量，可以尝试其他降采样方法，如 farthest point sampling

**Comment by Hanwey2333** [comment]
> 降采样后每个文件的 event 数量不是固定 2048，只是平均 2048。

请问不是固定2048，而是平均2048是指降采样后事件数量并不固定，输入图网络的点数量也不固定吗？

**Comment by zhangxiann** [comment]
是的
