### ISSUE TITLE
预训练模型问题

### ISSUE THREAD

**Issue by X-ray0214** [zhangxiann/TPAMI_Gait_Identification#5]
您好，下载了您提供的预训练模型EV_Gait_3DGraph1.pkl后放到test_3d_graph.py测试时提示缺少一些键值，Missing key(s) in state_dict: "conv1.root.weight", "block1.left_conv1.root.weight", "block1.left_conv2.root.weight", "block1.shortcut_conv.root.weight", "block2.left_conv1.root.weight", "block2.left_conv2.root.weight", "block2.shortcut_conv.root.weight", "block3.left_conv1.root.weight", "block3.left_conv2.root.weight", "block3.shortcut_conv.root.weight".
请问是什么原因

**Comment by zhangxiann** [comment]
不知道，我没这个问题。那你重新训练吧

**Comment by zhangxiann** [comment]
可能是 pytorch 版本问题，我用的 pytorch 版本是 1.8.0
