### ISSUE TITLE
与训练模型验证问题

### ISSUE THREAD

**Issue by yanhan13944047669** [zhangxiann/TPAMI_Gait_Identification#6]
您好
下载您提供的模型后，运行报错
AttributeError: module 'torch.nn' has no attribute 'UninitializedParameter'
请问是什么问题？

**Comment by zhangxiann** [comment]
`pyTorch` 版本是多少？1.8.0 是 OK 的

**Comment by yanhan13944047669** [comment]
> `pyTorch` 版本是多少？1.8.0 是 OK 的

作者您好  在提高pytorch版本后解决了上述问题 谢谢
在我试图训练文中提出的cnn模型时，运行train_gait_cnn报错：
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\UserData\\yanhan\\RE-ID CO\\Event-Stream\\TPAMI_Gait_Identification-main\\TPAMI_Gait_Identification-main\\log\\cnn_train_four_channel.log'
请问是什么原因呢？
望解答 谢谢。

**Comment by zhangxiann** [comment]
试试创建“log”文件夹。。
