### ISSUE TITLE
file missing: environments.py

### ISSUE THREAD

**Issue by kiwichen2003** [zhangxiann/TPAMI_Gait_Identification#7]
Hi, 

When run EV-Gait-IMG/gait_cnn_tf.py, there is one file missing.
>>environments.py.

thanks,

**Comment by zhangxiann** [comment]
As described in the README and our paper, we only provide the PyTorch version. 
We don't guarantee that the code of tf version is runnable. 
But we welcome the implementing and pull request for the code of the tf version.

**Comment by kiwichen2003** [comment]
thank you for the reply.
